config/routes.rb
Rails.application.routes.draw do
  root 'web#index'
  get 'search' => 'web#web_results'
  get 'image_search' => 'web#image_results'
  get 'images' => 'web#images'

end

app/models/search.rb
class Search < ActiveRecord::Base

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/web_controller.rb
class WebController < ApplicationController
  def index
 		
    # if params[:q]
    #   # page = params[:page] || 1
    #   @results = GoogleCustomSearchApi.search(params[:q])
    # end
  end

  def images
  end

  def web_results
  	if params[:q]
      page = params[:page] || 1
      @results = GoogleCustomSearchApi.search(params[:q])
    end
  end

  def image_results
    if params[:q]
      page = params[:page] || 1
      @results = GoogleCustomSearchApi.search(params[:q])
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Doogle</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class= "container">
	<%= yield %>
</div>


</body>
</html>

app/views/web/image_results.html.erb
<!--image search results go here-->
<%= form_tag image_search_path, method: :get  do %>
  <%= text_field_tag :q, params[:q] %>
  <%= submit_tag "Search" %>
<% end %>

<% if @results && !@results.items.empty? %>

	<% @results.items.each do |item| %>
          
     	<% if item['pagemap'] && item['pagemap']['cse_thumbnail'] && img = item.pagemap.cse_thumbnail.first %>
              
      <%= link_to image_tag(img.src, width: '200px'), item.link %>
      
      <% end %>

  <% end %>

		<% if @results.previous_page %>
		  <%= link_to '<< Previous', image_search_path(q: params[:q], page: @results.previous_page)%>
		  <% end %>

		<% @results.pages.times do |i| %>
		  <%= link_to i + 1, image_search_path(q: params[:q], page: i+1) %>
		<% end %>
		      
		<% if @results.next_page %>
		  <%= link_to 'Next >>', image_search_path(q: params[:q], page: @results.next_page) %>
		<% end %>

<% else %>
  <h4>No results</h4>
<% end %>

app/views/web/images.html.erb
<!--This is the image search page-->
<%= form_tag image_search_path, method: :get  do %>
  <%= text_field_tag :q, params[:q] %>
  <%= submit_tag "Search" %>
<% end %>

app/views/web/index.html.erb
<!--This is the home page-->
<div class= "home-layout">
  
  <%= image_tag("logo.png", :alt => "logo", class: "home-logo") %>
  <%= form_tag search_path, method: :get  do %>

    <div class = "query">
      <div class = "form-group">      
        <%= text_field_tag :q, params[:q], class: "search-bar form-control" %>
      </div>

      <div class= "search-btn">
        <%= submit_tag "Search", class: "btn btn-info" %>
      </div>
    </div>
    
  <% end %>
</div>

app/views/web/web_results.html.erb
<div class= "results-page">
<!-- <div class= "hey"> -->


  <%= form_tag search_path, method: :get  do %>
  <div class= "form-group somethin"> 
    <%= link_to image_tag("doogle-search.png", :alt => "logo", class: "search-logo"), root_path %>     
    <%= text_field_tag :q, params[:q], class: "results-search form-control" %>
    <%= submit_tag "Search", class: "btn btn-info" %>
  </div>
  <% end %>
<!-- </div> -->
<nav class="navbar navbar-default oi">
  <div class= "navbar-header">
    <ul class= "nav navbar-nav">
      <li><%= link_to "Web", search_path(q: params[:q], page: @results) %></li>
      <li><%= link_to "Images", image_search_path(q: params[:q], page: @results) %></li>
  </div>
</nav>
<br />
  <div class= "results-body">

    <% if @results && !@results.items.empty? %>

    	<% @results.items.each do |item| %>
        <div class= "hotlink">   
      		<h4 class= "link_title"><%= link_to item.htmlTitle.html_safe, item.link %></h4>
          <p class= "url"><%=  item.link%></p> 
                
           	<% if item['pagemap'] && item['pagemap']['cse_thumbnail'] && img = item.pagemap.cse_thumbnail.first %>
                    
              <%#= image_tag(img.src, width: '200px') %>
              <%= item.htmlSnippet.html_safe %>
                    
            <% else %>
              <%= item.htmlSnippet.html_safe %>
            <% end %>
      </div>
           
      <% end %>
  </div>
        <div class= "pages">
     
          <% if @results.previous_page %>
            <%= link_to '<< Previous', search_path(q: params[:q], page: @results.previous_page)%>
          <% end %>

          <% @results.pages.times do |i| %>
            <%= link_to i + 1, search_path(q: params[:q], page: i+1) %>
          <% end %>
          
          <% if @results.next_page %>
            <%= link_to 'Next >>', search_path(q: params[:q], page: @results.next_page) %>
          <% end %>

        </div>
        
  <% else %>
    <h4>No results</h4>

  <% end %>

</div>